version: 1
services:
  - type: web
    name: mailing-service-web
    env: node
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_DB
        sync: false
      - key: WORKER_CONCURRENCY
        sync: false
      - key: NEXT_PUBLIC_RUN_WORKER_IN_PR
        sync: false

  - type: worker
    name: mailing-service-worker
    env: node
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run render-worker
    plan: free
    envVars:
      # all your ENV variables here too!
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_DB
        sync: false
      - key: WORKER_CONCURRENCY
        sync: false
      - key: NEXT_PUBLIC_RUN_WORKER_IN_PR
        sync: false
